### ISSUE TITLE
Boolean conversion missing

### ISSUE THREAD

**Issue by yamen** [fdieulle/pandasnet#2]
`bool[]` is supported from .NET to Python:

https://github.com/fdieulle/pandasnet/blob/ea44ebe832f21fd85a057f3e902f23b839685666/dotnet/PandasNet/NumpyCodec.cs#L17

But it's missing from `GetDType`:

https://github.com/fdieulle/pandasnet/blob/ea44ebe832f21fd85a057f3e902f23b839685666/dotnet/PandasNet/NumpyCodec.cs#L128-L158

Causing an engine crash in my python when trying to convert boolean arrays. I think I've debugged correctly?

**Comment by fdieulle** [comment]
Thanks for this point.
This issue is solved in version 0.6
